
package view;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

// abstract class that contains some methods that are useful
// for the most of the internal frames
public abstract class AbstractJInternalFrame extends javax.swing.JInternalFrame {
    
    // constructor
    public AbstractJInternalFrame() {
        initComponents();
    }
    
    // method that clears the contents of the given DefaulttableModel object
    public void ClearJTable(DefaultTableModel tableModelObject){
       
            if (tableModelObject.getRowCount()!= 0)
                for(int currentRowIndex = tableModelObject.getRowCount() - 1; currentRowIndex >=0;
                                                                                currentRowIndex--){
                    tableModelObject.removeRow(currentRowIndex);   
            }  
    }
    
    // method that clears the contents of the given DefaultListModel object
    public void ClearJList(DefaultListModel<String> DefaultListModelObject){
            if (!DefaultListModelObject.isEmpty())
                    DefaultListModelObject.removeAllElements();
    }
    
    // method that clears the content of the given JComponent object
    public void clearForm(List<JComponent> componentsList){
        for (JComponent currentJComponentObject: componentsList)
            if (currentJComponentObject instanceof JTextField)
                ((JTextField)currentJComponentObject).setText("");
            else if (currentJComponentObject instanceof JLabel)
                ((JLabel)currentJComponentObject).setText("");
            else
                ((JRadioButton)currentJComponentObject).setSelected(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
