
package view;

import adjustedClasses.StaticShower;
import enums.InternalFrameName;
import exceptions.InvalidAddBecauseOfLimit;
import javax.swing.DefaultListModel;
import model.Championship;

public class SolistParticipationInternalFrame extends AbstractParticipationsInternalFrame {
    
    public SolistParticipationInternalFrame() {
        initComponents();
        
        createModels();
    }
    
    private DefaultListModel<String> availableSolistsDefaultListModelObject = null;
    private DefaultListModel<String> inSolistsDefaultListModelObject = null;
    
    public void createModels(){
        
        this.availableSolistsDefaultListModelObject = new DefaultListModel<>();
        this.availableSolistsList.setModel(availableSolistsDefaultListModelObject);
        
        this.inSolistsDefaultListModelObject = new DefaultListModel<>();
        this.inSolistsList.setModel(inSolistsDefaultListModelObject);
    }
    
    public void updateInternalFrame(){
        
        super.updateInternalFrame(availableSolistsDefaultListModelObject, inSolistsDefaultListModelObject);
    }
    
    public void updateVisibilityOfInOutButtons(){
    
        if (this.controllerObject.isChampionshipObjectFinalized()){
            this.inSolistsButton.setEnabled(false);
            this.outSolistsButton.setEnabled(false);
        }
        else{
            this.inSolistsButton.setEnabled(true);
            this.outSolistsButton.setEnabled(true);
        }
              
    }
    
    public void updateInternalFrameForInOrForOutAvailableButtonUsed(){
        
        this.solistsInTextField.setText(this.controllerObject.getChampionshipObject().
                                                                    getNumberOfCompetitors().toString());
        
        
        super.updateInternalFrameForInOrForOutAvailableButtonUsed(availableSolistsDefaultListModelObject,
                                                                            inSolistsDefaultListModelObject);
    }
    
    public void updateInfoPanel(){
        
        Championship championshipObject = this.controllerObject.getChampionshipObject();
        
        this.championshipLabel.setText(championshipObject.toString());
        
        String minRosterTostring = championshipObject.getMinRoster().toString();
        this.basicInfoLabel.setText(minRosterTostring + "vs" + minRosterTostring +
                                    " " + championshipObject.getSport().toString() +
                                    " " + championshipObject.getChampionshipTypeString());
        
        this.solistsInTextField.setText(championshipObject.getNumberOfCompetitors().toString());
        this.limitSolistsLabel.setText("(Limit: " + championshipObject.getNumberOfCompetitorsBigO().toString()+ ")");
        
        this.writeParticipationsGuideString();
    }
    
    public void updateAvailableCompetitorsList(){
        
        super.updateAvailableCompetitorsList(availableSolistsDefaultListModelObject);
    }
    
    public void updateInCompetitorsList(){
        
        super.updateInCompetitorsList(inSolistsDefaultListModelObject);
    }
    
    public void writeParticipationsGuideString(){
        this.guideTextArea.setText(this.controllerObject.getParticipationsGuideString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        limitSolistsLabel = new javax.swing.JLabel();
        solistsInTextField = new javax.swing.JTextField();
        championshipLabel = new javax.swing.JLabel();
        basicInfoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        availableSolistsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableSolistsList = new javax.swing.JList<>();
        solistsButtonPanel = new javax.swing.JPanel();
        inSolistsButton = new javax.swing.JButton();
        outSolistsButton = new javax.swing.JButton();
        inSolistsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inSolistsList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        guideTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        infoPanel.setBackground(new java.awt.Color(201, 195, 168));
        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 0, 0)), "Championship", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        jLabel5.setText("Solists In");

        solistsInTextField.setEditable(false);

        championshipLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(basicInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solistsInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limitSolistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(championshipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(championshipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limitSolistsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(solistsInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(201, 195, 168));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setForeground(java.awt.Color.blue);
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(java.awt.Color.blue);
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(201, 195, 168));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 0, 0)), "Solists application", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        availableSolistsPanel.setBackground(new java.awt.Color(201, 195, 168));
        availableSolistsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Available Solists"));

        availableSolistsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(availableSolistsList);

        javax.swing.GroupLayout availableSolistsPanelLayout = new javax.swing.GroupLayout(availableSolistsPanel);
        availableSolistsPanel.setLayout(availableSolistsPanelLayout);
        availableSolistsPanelLayout.setHorizontalGroup(
            availableSolistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableSolistsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        availableSolistsPanelLayout.setVerticalGroup(
            availableSolistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, availableSolistsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        solistsButtonPanel.setBackground(new java.awt.Color(201, 195, 168));

        inSolistsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inSolistsButton.setForeground(java.awt.Color.blue);
        inSolistsButton.setText("In");
        inSolistsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSolistsButtonActionPerformed(evt);
            }
        });

        outSolistsButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        outSolistsButton.setForeground(java.awt.Color.blue);
        outSolistsButton.setText("Out");
        outSolistsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outSolistsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout solistsButtonPanelLayout = new javax.swing.GroupLayout(solistsButtonPanel);
        solistsButtonPanel.setLayout(solistsButtonPanelLayout);
        solistsButtonPanelLayout.setHorizontalGroup(
            solistsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solistsButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solistsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outSolistsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inSolistsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        solistsButtonPanelLayout.setVerticalGroup(
            solistsButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solistsButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inSolistsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outSolistsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inSolistsPanel.setBackground(new java.awt.Color(201, 195, 168));
        inSolistsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Solists in"));

        inSolistsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(inSolistsList);

        javax.swing.GroupLayout inSolistsPanelLayout = new javax.swing.GroupLayout(inSolistsPanel);
        inSolistsPanel.setLayout(inSolistsPanelLayout);
        inSolistsPanelLayout.setHorizontalGroup(
            inSolistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inSolistsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );
        inSolistsPanelLayout.setVerticalGroup(
            inSolistsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inSolistsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(availableSolistsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solistsButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inSolistsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(solistsButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 304, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inSolistsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(availableSolistsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jLabel9.setBackground(new java.awt.Color(201, 195, 168));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("Participation - Solist");

        jPanel3.setBackground(new java.awt.Color(201, 195, 168));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 0, 0)), "Short advice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), java.awt.Color.blue)); // NOI18N

        guideTextArea.setEditable(false);
        guideTextArea.setBackground(new java.awt.Color(201, 195, 168));
        guideTextArea.setColumns(10);
        guideTextArea.setRows(1);
        guideTextArea.setBorder(null);
        jScrollPane3.setViewportView(guideTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesUI/weCanDoIt_smallb&w.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.updateInternalFrame();
        updateVisibilityOfInOutButtons();
    }//GEN-LAST:event_formComponentShown

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.controllerObject.showInternalFrameObject(InternalFrameName.CHAMPIONSHIPINTERNAL);
    }//GEN-LAST:event_backButtonActionPerformed

    private void inSolistsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSolistsButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            if (this.availableSolistsList.getSelectedIndex() ==-1)
                throw new NullPointerException();
            
            super.checkForInvalidAddBecauseOfLimit("solists");
           
            this.controllerObject.addCompetitorToChampionship(this.controllerObject.getSelectedCompetitor
                                                (this.availableSolistsList.getSelectedValue().toString()));
            updateInternalFrameForInOrForOutAvailableButtonUsed();
            this.writeParticipationsGuideString();
        }
        catch(NullPointerException e){
            StaticShower.showWarningMessage(StaticShower.NOT_EXACTLY_ONE_LINE + 
                                                            " from \"Available Solists\" list");
        }
        catch(InvalidAddBecauseOfLimit e){
            StaticShower.showWarningMessageForInvalidInput(e);
        }
    }//GEN-LAST:event_inSolistsButtonActionPerformed

    private void outSolistsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outSolistsButtonActionPerformed
        
        try{
            if (this.inSolistsList.getSelectedIndex() ==-1)
                throw new NullPointerException();
            
            this.controllerObject.removeCompetitorFromChampionship(this.inSolistsList.getSelectedIndex());
            updateInternalFrameForInOrForOutAvailableButtonUsed();
            this.writeParticipationsGuideString();
        }
        catch(NullPointerException e){
            StaticShower.showWarningMessage(StaticShower.NOT_EXACTLY_ONE_LINE + 
                                                            " from \"Solists in\" list");
        }
    }//GEN-LAST:event_outSolistsButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        this.controllerObject.serialize();
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> availableSolistsList;
    private javax.swing.JPanel availableSolistsPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel basicInfoLabel;
    private javax.swing.JLabel championshipLabel;
    private javax.swing.JTextArea guideTextArea;
    private javax.swing.JButton inSolistsButton;
    private javax.swing.JList<String> inSolistsList;
    private javax.swing.JPanel inSolistsPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel limitSolistsLabel;
    private javax.swing.JButton outSolistsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel solistsButtonPanel;
    private javax.swing.JTextField solistsInTextField;
    // End of variables declaration//GEN-END:variables
}
